### ISSUE TITLE
Cash App Pay

### ISSUE THREAD

**Issue by motikolorado** [Ching-Inc/add-cash-app-pay#1]
Please I am having issues intigrating this cash app pay button on my static website. I am not using nodeJs, Just single static HTML page. I see you hosted your backend on heroku. Please can you upload your backend source on github so i can fork it and use my own access code. I have tried a lot of tutorials but you are the only one that come close to what am working on. Its a simple donation page that lets people input any amount and donate with cash app....

I have been hooked on showing the token on the screen.

**Comment by motikolorado** [comment]
Please just share your backend server code for processing the cash app payment requset. Just remove your access token from the .env file and leave the file.
Basically just the template so i can just fork this repo and the server repo, then add my IDs and Token and host the backend.
Thank you.

**Comment by uyito** [comment]
I am sorry I am just see this. please if you still need this please let me know so i can send it @motikolorado

**Comment by motikolorado** [comment]
I have found an alternative, thanks.
